#!/bin/bash
_psearch()
{
    project_folder="/home/god/projects"
    depth=3
    base_folder=$(basename $project_folder)
    local cur=${COMP_WORDS[COMP_CWORD]}
    local prev=${COMP_WORDS[COMP_CWORD-1]}
    local all_options=()
    local cmd_options=("-l -g -c -a -r -b -h")
    if [ $COMP_CWORD -eq 1 ]; then
	    folders=`find $project_folder -maxdepth $((depth-1)) -type d | grep -v '\.git'| sed 's/.*\///'|sed ':a;N;$!ba;s/\n/ /g'`
      folders="$(for l in ${folders[@]}; do echo $l; done | sort)"
      cmd_options="$(for l in ${cmd_options[@]}; do echo $l; done | sort)"
      all_options+=( "$base_folder ${cmd_options[*]} ${folders[*]}" )
    elif [ "$prev" == "-l" ] || [ "$prev" == "--list" ]; then
      folders=`find $project_folder -maxdepth $((depth-2)) -type d | grep -v '\.git'| sed 's/.*\///'|sed ':a;N;$!ba;s/\n/ /g'`
      folders="$(for l in ${folders[@]}; do echo $l; done | sort)"
      all_options+=( "languages ${folders[*]}" )
    elif [ "$prev" == "-g" ] || [ "$prev" == "--get" ]; then
	    folders=`find $project_folder -maxdepth $((depth-1)) -type d | grep -v '\.git'| sed 's/.*\///'|sed ':a;N;$!ba;s/\n/ /g'`
      folders="$(for l in ${folders[@]}; do echo $l; done | sort)"
      all_options+=( "$base_folder ${folders[*]}" )
    elif [ "$prev" == "-c" ] || [ "$prev" == "--create" ]; then
      folders=`find $project_folder -maxdepth $((depth-2)) -type d | grep -v '\.git'| sed 's/.*\///'|sed ':a;N;$!ba;s/\n/ /g'`
      folders="$(for l in ${folders[@]}; do echo $l; done | sort)"
      all_options+=( "${folders[*]}" )
    elif [ "$prev" == "-r" ] || [ "$prev" == "--remove" ]; then
	    folders=`find $project_folder -maxdepth $((depth-1)) -type d | grep -v '\.git'| sed 's/.*\///'|sed ':a;N;$!ba;s/\n/ /g'`
      folders="$(for l in ${folders[@]}; do echo $l; done | sort)"
      all_options+=( "${folders[*]}" )
    fi
    COMPREPLY=( $(compgen  -W "$all_options" -- $cur) )
}
complete -o nosort -F _psearch psearch
