#!/bin/bash
folder="/home/god/projects" #Your project folder
backup_exec="/home/god/backups/backup"
basefolder=$(basename $folder)

if [ "$folder" = "" ]; then
  echo "Please specify a project folder"
  return
fi
if [ "$backup_exec" = "" ]; then
  echo "Please specify a backup executable"
  return
fi

ps_help(){
  echo "psearch is a program to naviagte your project folder: \"$folder\""
  echo "Here is a list of its commands:"
  echo "  psearch [project]               |  Finds a project with the given name"
  echo "                                  -  and goes to that directory"
  echo "  psearch -l [language]           |  Lists all projects of a given language,"
  echo "                                  -  leave blank to just list languages"
  echo "  psearch -c [language] [project] |  Creates a new project in the given"
  echo "             [file]               -  language with the given names"
  echo "  psearch -a [language]           |  Add a new language folder"
  echo "  psearch -r [project]            |  Remove a project folder"
  echo "  psearch -b [project]            |  Backup your project folder"

  echo "  psearch -help [language]        |  Brings up this message"
}

ps_backup(){
  bash $backup_exec
}

ps_list(){
  if [ ! -d "$folder/$2" ] && [ "$2" != "languages" ]; then
    echo "The language \"$2\" was not found"
    return
  fi
  if [ "$2" = "" ]; then
    found=`find "$folder/$2" -maxdepth 2 -mindepth 2 -type d | grep -v .git |cut -d/ -f5-`
    mapfile -t array <<< "$found"
    for item in ${array[@]:1}
    do
      echo "$item"
    done
  elif [ "$2" = "languages" ]; then
    found=`find "$folder" -maxdepth 1  -type d | grep -v .git|cut -d/ -f4-`
    mapfile -t array <<< "$found"
    for item in ${array[@]:1}
    do
      echo "$item"
    done
  else
    found=`find "$folder/$2" -maxdepth 1 -mindepth 1 -type d | grep -v .git |cut -d/ -f5-`
    mapfile -t array <<< "$found"
    for item in ${array[@]:1}
    do
      echo "$item"
    done
  fi
}
ps_add(){
  if [ -d "$folder/$2" ]; then
    echo "The language \"$2\" already exists"
    echo "Going to \"$basefolder/$2\""
    cd $folder/$2
    return
  else
    mkdir "$folder/$2"
    echo "Created a folder for the language \"$2\""
    echo "Going to \"$basefolder/$2\""
    cd $folder/$2
    return
  fi
}

ps_create(){
  if [ "$3" = "" ]; then
    echo "Please specify a project name"
    return
  fi
  if [ -d "$folder/$2/$3" ]; then
    echo "The project \"$2/$3\" already exits"
    cd $folder/$2/$3
    return
  elif [ ! -d $folder/$2 ]; then
    echo "Language $2 does not exist"
  else
    mkdir "$folder/$2/$3"
    if [ "$4" = "" ]; then
      file_name="$3"
    else
      file_name=`echo $4 | sed 's/\.[^.]*$//'`
    fi
    case "$2" in
    bash) touch $folder/$2/$3/$file_name
        echo "#!/bin/bash" >> $folder/$2/$3/$file_name
        chmod +x $folder/$2/$3/$file_name
        ;;
    c) touch $folder/$2/$3/$file_name.c
        ;;
    python) touch $folder/$2/$3/$file_name.py
        ;;
    javascript)
        touch $folder/$2/$3/$file_name.js
        touch $folder/$2/$3/index.html
        touch $folder/$2/$3/style.css
        ;;
    go) touch $folder/$2/$3/$file_name.go
        ;;
    c++) touch $folder/$2/$3/$file_name.cpp
	       ;;
    esac
    echo "Created the project \"$2/$3/$file_name\""
    echo "Going to \"$2/$3\""
    cd $folder/$2/$3
    return
  fi

}

ps_remove(){
  found=`find $folder -maxdepth 2 -type d | grep -v .git | grep './'$2'$'`
  found=${found//[.]\//$folder/}
  len=`echo "$found"| wc -l`
  mapfile -t array <<< "$found"
  if [ "$found" = "" ]; then
    echo "No projects with name \"$2\" found"
    echo "Try finding a project using \"psearch -l [language]\"..."
  elif [ $len -gt 1 ]; then
    echo "Multiple instances found, please select a language..."
    i=0
    for item in ${array[@]}
    do
      i=$((i+1))
      item=$(basename $(dirname $item))
      echo "[$i]: $item"
    done
    read -p "Selection: " choice
    choice=$((choice-1))
    read -p "Are you sure you want to delete \"$(basename $(dirname ${array[$choice]}))/$(basename ${array[$choice]})\" (y/n): " are_you_sure
    if [ "$are_you_sure" = "y" ]; then
      read -p "THIS WILL DELETE \"$(basename $(dirname ${array[$choice]}))/$(basename ${array[$choice]})\" (y/n): " are_you_sure
      if [ "$are_you_sure" = "y" ]; then
        echo "Deleting \"$(basename $(dirname ${array[$choice]}))/$(basename ${array[$choice]})\""
        rm -rf ${array[choice]}
        if [ "$PWD" = "$found" ]; then
          cd $(dirname "$found")
        fi
      else
        echo "Not deleting"
        return
      fi
    return
    else
      echo "Not deleting"
      return
    fi
  else
    read -p "Are you sure you want to delete \"$(basename $(dirname $found))/$(basename $found)\" (y/n): " are_you_sure
    if [ "$are_you_sure" = "y" ]; then
      read -p "THIS WILL DELETE \"$(basename $(dirname ${array[$choice]}))/$(basename ${array[$choice]})\" (y/n): " are_you_sure
        if [ "$are_you_sure" = "y" ]; then
          echo "Deleting \"$(basename $(dirname $found))/$(basename $found)\""
          rm -rf ${array[choice]}
          if [ "$PWD" = "$found" ]; then
            cd $(dirname "$found")
          fi
          return
        else
          echo "Not deleting"
          return
        fi
    else
      echo "Not deleting"
      return
    fi
  fi
}

ps_search(){
  found=`find $folder -maxdepth 2 -regex ".*/$1"  -type d | grep -v .git`
  found=${found//[.]\//$folder/}
  len=`echo "$found"| wc -l`
  mapfile -t array <<< "$found"
  if [ "$found" = "" ]; then
  echo "No projects with name \"$1\" found"
  echo "Try finding a project using \"psearch -l [language]\"..."
  echo "Or create a new project using \"psearch -c [language] [name]\""
  elif [ "$len" -gt "1" ]; then
    echo "Multiple instances found, please select a language..."
    i=0
    for item in ${array[@]}
    do
      i=$((i+1))
      item=$(basename $(dirname $item))
      echo "[$i]: $item"
    done
    read -p "Selection: " choice
    choice=$((choice-1))
    echo "Going to \"$(basename $(dirname ${array[$choice]}))/$(basename ${array[$choice]})\""
    cd ${array[$choice]}
  else
    echo "Going to \"$(basename $(dirname $found))/$(basename $found)\""
    cd $found
  fi
}

if [ "$1" = "-help" ]; then #Help
 ps_help $1 $2 $3 $4
elif [ "$1" = "-b" ]; then #Backup
  ps_backup $1 $2 $3 $4
elif [ "$1" = "-l" ]; then #Listing
  ps_list $1 $2 $3 $4
elif [ "$1" = "-a" ]; then #Adding a new language folder
  ps_add $1 $2 $3 $4
elif [ "$1" = "-c" ]; then #Creating a new project
  ps_create $1 $2 $3 $4
elif [ "$1" = "-r" ]; then #Removing a project
  ps_remove $1 $2 $3 $4
elif [ "$1" != "" ]; then #Finding and going to a project
  ps_search $1 $2 $3 $4
else #Lists a project if given no paramaters
  ps_list $1 $2 $3 $4
fi
